# Generated by Django 5.1.4 on 2025-03-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image_url',
            field=models.URLField(default='https://example.com/default-image.jpg'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
