# Generated by Django 5.1.4 on 2025-03-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_episodes_alter_anime_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
