# Generated by Django 5.1.4 on 2025-03-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_episodes_alter_anime_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='kitsu_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
