# Generated by Django 5.1.4 on 2025-03-02 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_anime_kitsu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='mal_id',
            new_name='anilist_id',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='kitsu_id',
        ),
    ]
